name: muscle_training
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.3
  hooks_riverpod: ^2.3.3
  go_router: ^6.5.5
  freezed: ^2.3.2
  device_preview: ^1.1.0
  table_calendar: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
